name:                anzan
version:             0.1.0.0
github:              "qoelet/anzan"
license:             BSD3
author:              "Kenny Shen"
maintainer:          "kenny@machinesung.com"
copyright:           "2018 Kenny Shen"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/qoelet/anzan#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- random
- vty

library:
  source-dirs: src

executables:
  anzan:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - anzan
